version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: primapulih-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: primapulih
    ports:
      - "5432:5432"
    volumes:
      - ./supabase/migrations/0001_initial_schema.sql:/docker-entrypoint-initdb.d/0001_initial_schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
