services:
  db:
    image: postgres:15-alpine
    container_name: primapulih-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: primapulih
    ports:
      - "5435:5432"
    volumes:
      - ./database/0001_initial_schema.sql:/docker-entrypoint-initdb.d/0001_initial_schema.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend_go
    container_name: primapulih-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=primapulih
      - DB_SSLMODE=disable
    depends_on:
      - db

volumes:
  postgres_data:
